### ISSUE TITLE
how does this compare to the builtin riot2.0 router?

### ISSUE THREAD

**Issue by coderofsalvation** [crisward/riot-routehandler#2]
see http://riotjs.com/api/route/

**Comment by crisward** [comment]
The built in router is more an event emitter. Ie, it calls you back when a route changes and lets you do something. The route handler is built around something like that (page.js). I used page instead of the built in router because at the time the riot router was too simplistic for my needs. Page.js also reflects the express api, which as a node developer I am familiar with.

Riot-routehandler is more that just an event system, it allows you to have a tag of your choice inserted into the document when a route is navigated too. Client side applications typically use the router as a backbone to application state, so if you navigate to a url, the applications state is consistent for that location. I think this is easier to achieve if it's tags all the way down... Once your routes are declared you just need to define a bunch of tags and link them up to the right routes. It helps make constructing complex applications much simpler.

It was heavily inspired by using routers in other frameworks, ie React and Angular, though it's not nearly as sophisticated, embodying only the feature I needed for the project I built it for. Though I'm happy when it makes sense to add to it's feature set.

https://github.com/angular-ui/ui-router
https://github.com/rackt/react-router

**Comment by coderofsalvation** [comment]
```
> Riot-routehandler is more that just an event system, it allows you to have a tag of your choice 
> inserted into the document when a route is navigated too. 
```

Funny, after writing this issue I started writing an riot app.
This is exactly the problem I was running into.
My workaround was to have empty tags sitting around all the time, and populating/emptying them upon  routing (which quickly becomes hairy when adding more and more pages)
Now looking at your answer and riot-routehandler I realize I need this :)
thx.

Leon.
